# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

api_print <- function() {
    invisible(.Call(`_RcppScratch_api_print`))
}

api_exit <- function() {
    invisible(.Call(`_RcppScratch_api_exit`))
}

api_stderr <- function() {
    invisible(.Call(`_RcppScratch_api_stderr`))
}

api_myerr <- function() {
    invisible(.Call(`_RcppScratch_api_myerr`))
}

plus_one <- function(x) {
    .Call(`_RcppScratch_plus_one`, x)
}

api_plus_one <- function(x) {
    .Call(`_RcppScratch_api_plus_one`, x)
}

rcpp_hello_world <- function() {
    .Call(`_RcppScratch_rcpp_hello_world`)
}

test_api_class <- function() {
    invisible(.Call(`_RcppScratch_test_api_class`))
}

